#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

calibre_library_dir="$data_dir/eBook"
ynh_app_setting_set --key="calibre_library_dir" --value="$calibre_library_dir"

timezone=$(timedatectl show --value --property=Timezone)

cwa_release=$(ynh_app_upstream_version)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

#Set settings constant initializer of the app (variables aren’t updated otherwise)
#ynh_config_add --template="../patches/cwa/ub.py.patch.src" --destination="../patches/cwa/ub.py.patch"

ynh_script_progression "Setting up cwa..."
ynh_setup_source --dest_dir="$install_dir/cwa"

# Install kepubify converter
ynh_script_progression "Setting up kepubify..."
ynh_setup_source --dest_dir="$install_dir/tools" --source_id="kepubify"

# Install Calibre
ynh_script_progression "Setting up Calibre..."
ynh_setup_source --dest_dir="$install_dir/tools/calibre" --source_id="calibre"

pushd "$install_dir/tools/calibre"
	tar -xvf calibre.txz
popd

chown -R $app:$app $install_dir
chmod -R 770 $install_dir/tools

#=================================================
# CREATE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Creating files and directory..."

#build multimedia directory
ynh_multimedia_build_main_dir
ynh_multimedia_addaccess $app

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

ynh_replace --match="add_missing_tables(engine, _session)" --replace="add_missing_tables(engine, _session)\n  create_admin_user(_session)" --file="$install_dir/cwa/cps/ub.py"
ynh_replace --match="user.name = "admin"" --replace="user.name = "$admin"" --file="$install_dir/cwa/cps/ub.py"
ynh_replace --match="user.email = "admin@example.org"" --replace="user.email = "$admin_mail"" --file="$install_dir/cwa/cps/ub.py"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Setting up system configuration..."

#Cannot use empty string for X-script-name, causes an issue in the python prg
#https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx
if [ $path = "/" ] ; then
	ynh_replace --match="        proxy_set_header	X-Script-Name		__PATH__;" \
	            --replace="        proxy_set_header	X-Script-Name		/__PATH__;" \
	            --file="../conf/nginx.conf"
fi

#
if $(ynh_permission_has_user --permission=main --user=visitors); then
	ynh_replace --match="        proxy_set_header	X-Remote-User" \
	            --replace="#       proxy_set_header	X-Remote-User" \
	            --file="../conf/nginx.conf"
fi

# Create a dedicated nginx config
ynh_config_add_nginx


#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Starting patching operations..."
_ynh_patch_cwa

ynh_script_progression "Installing pip requirements..."

pushd "$install_dir/cwa"
	ynh_exec_as_app python3 -m venv "$install_dir/cwa/venv"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/cwa/venv/bin/pip" install --upgrade wheel pip setuptools
	ynh_hide_warnings ynh_exec_as_app "$install_dir/cwa/venv/bin/pip" install --no-cache-dir --upgrade --use-pep517 -r "$install_dir/cwa/requirements.txt"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/cwa/venv/bin/pip" install --no-cache-dir --upgrade --use-pep517 -r "$install_dir/cwa/optional-requirements.txt"

	find cps -type f -name "*.py" -exec sed -i 's#/app/calibre-web-automated#'"$install_dir/cwa"'#g' {} \;
	find scripts -type f -name "*.py" -exec sed -i 's#/app/calibre-web-automated#'"$install_dir/cwa"'#g' {} \;

	# Compile translations, otherwise we only have English
	ynh_hide_warnings bash scripts/compile_translations.sh
popd

chmod +x "$install_dir/cwa/scripts/"*.sh || true
chmod +x "$install_dir/cwa/scripts/"*.py || true
chmod 775 "$install_dir/cwa/cps/"*.py || true

pushd "$install_dir/cwa/scripts"
  $install_dir/cwa/venv/bin/python3 auto_library.py
popd

ynh_script_progression "Creating koplugin.zip from KOReader plugin folder......"
_ynh_create_koplugin

chown -R $app:$app $install_dir
  
#=================================================
# SETUP LOGROTATE
#=================================================
# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$log_file"
ynh_config_add_logrotate "$access_log_file"

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression "Configuring Fail2Ban..."

# Make sure a log file exists (mostly for CI tests)
 if [ ! -f "$log_file" ]; then
	touch "$log_file"
	chown $app: "$log_file"
fi

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="$log_file" --failregex="^.*LDAP Login failed for user .* IP-address: <HOST>.*$"

#=================================================
# UPDATE DATABASE
#=================================================
ynh_script_progression "Updating database with the right values..."

_ynh_adapt_cwa_db

#=================================================
# SETUP SYSTEMD
#=================================================

# Create a dedicated systemd config
ynh_config_add_systemd --service="${app}" --template="cwa.service"

yunohost service add "${app}" --description="CWA Browse eBook on the web" --log="$log_file"

#=================================================
# STARTING APP
#=================================================
ynh_script_progression "Start $app..."

ynh_systemctl --service="${app}" --action="start" --wait_until="Starting Gevent server on" -t 60

#Setting the proxy authentication in case calibre is not open to visitor.
#https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#login-via-header-from-upstream-authentication-source
#We need to update the sso login parameter, but for that the app needs to have run at least once to initialize the tables.
if ! $(ynh_permission_has_user --permission=main --user=visitors); then
	ynh_systemctl --service=$app --action="stop"
	sqlite3 $install_dir/config/app.db "UPDATE settings SET config_reverse_proxy_login_header_name='X-Remote-User', config_allow_reverse_proxy_header_login='True', config_allow_reverse_proxy_header_login=1 WHERE ID=1;"
	ynh_systemctl --service=$app --action="start" --wait_until="Starting Gevent server on"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
