#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

admin_mail=$(ynh_user_get_info --username="$admin" --key=mail)

if  [ $public_library -eq 1 ]; then
	calibre_library_dir=/home/yunohost.multimedia/share/eBook
else # library is private
	calibre_library_dir=$data_dir/eBook
fi

ynh_app_setting_set --key="calibre_library_dir" --value="$calibre_library_dir"


ingest_folder="$install_dir/ingest",
tmp_conversion_dir="$install_dir/config/.cwa_conversion_tmp"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir" --source_id="cwa"
ynh_setup_source --dest_dir="$install_dir/calibreweb" --source_id="calibreweb"

# Install kepubify converter
ynh_script_progression "Installing kepubify..."
ynh_setup_source --dest_dir="/opt/kepubify/$app/" --source_id="kepubify"

# Install Calibre
ynh_script_progression "Installing Calibre..."
ynh_setup_source --dest_dir="$install_dir/calibre/$app/" --source_id="calibre"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL DEPENDENCIES
#=================================================

pushd "$install_dir"
	ynh_exec_as_app python3 -m venv "$install_dir/venv"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade wheel pip setuptools
	ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --no-cache-dir --upgrade -r "$install_dir/requirements.txt"
	ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --no-cache-dir --upgrade -r "$install_dir/optional-requirements.txt"
popd

chmod +x "$install_dir/scripts/"*.sh || true
chmod +x "$install_dir/scripts/"*.py || true
chmod 775 "$install_dir/cps/"*.py || true

#=================================================
# CREATE FILES AND DIRECTORIES
#=================================================
ynh_script_progression "Creating files and directory..."

#build multimedia directory
ynh_multimedia_build_main_dir
ynh_multimedia_addaccess $app

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression "Setting up system configuration..."

#Cannot use empty string for X-script-name, causes an issue in the python prg
#https://github.com/janeczku/calibre-web/wiki/Setup-Reverse-Proxy#nginx
if [ $path = "/" ] ; then
	ynh_replace --match="        proxy_set_header	X-Script-Name		__PATH__;" \
	            --replace="        proxy_set_header	X-Script-Name		/__PATH__;" \
	            --file="../conf/nginx.conf"
fi

#
if $(ynh_permission_has_user --permission=main --user=visitors); then
	ynh_replace --match="        proxy_set_header	X-Remote-User" \
	            --replace="#       proxy_set_header	X-Remote-User" \
	            --file="../conf/nginx.conf"
fi

# Create a dedicated nginx config
ynh_config_add_nginx

#=================================================
# SETUP SYSTEMD
#=================================================

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# SETUP LOGROTATE
#=================================================
# Use logrotate to manage application logfile(s)
ynh_config_add_logrotate "$log_file"
ynh_config_add_logrotate "$access_log_file"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================

yunohost service add $app --description="Browse eBook in the web" --log="$log_file"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown -R $app: /opt/kepubify/$app
chmod 770 /opt/kepubify/$app/kepubify

chown -R $app: /opt/calibre/$app
chmod 770 /opt/calibre/$app/calibre

#=================================================
# SETUP FAIL2BAN
#=================================================
ynh_script_progression "Configuring Fail2Ban..."

# Make sure a log file exists (mostly for CI tests)
if [ ! -f "$log_file" ]; then
	touch "$log_file"
	chown $app: "$log_file"
fi

# Create a dedicated Fail2Ban config
ynh_config_add_fail2ban --logpath="$log_file" --failregex="^.*LDAP Login failed for user .* IP-address: <HOST>.*$"

#=================================================
# STARTING APP
#=================================================
ynh_script_progression "Start $app..."
ynh_systemctl --service=$app --action="start" --wait_until="Starting Gevent server on" -t 60

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
