name: Sync Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to sync"
        required: true
        default: "latest"

  push:
    tags:
      - "*"

  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      RELEASE_TAG: >-
        ${{
          github.event_name == 'workflow_dispatch' && inputs.tag ||
          github.ref_type == 'tag' && github.ref_name ||
          'latest'
        }}

    steps:
      - name: Show selected tag
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref:   ${{ github.ref }}"
          echo "Tag:   ${{ env.RELEASE_TAG }}"

      - name: Copy Release
        uses: aminya/sync-releases@v1
        with:
          source: kovidgoyal/calibre
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.RELEASE_TAG }}
